name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Run lint"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install -g turbo    
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      TEST_TIME_FACTOR: 10.0
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install -g turbo 
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
